### ISSUE TITLE
Automate import of required stemcell

### ISSUE THREAD

**Issue by guidowb** [guidowb/rebel#13]
A tile can remain orange if a required stemcell is not available in Ops Manager. At this point I'm not clear on where this dependency is encoded.

**Comment by guidowb** [comment]
The dependency information is in the .pivotal file. The file metadata/cf.yml contains the following properties:

```
stemcell_criteria:
  os: ubuntu-trusty
  version: '3112'
  requires_cpi: false
```

of course, rebel doesn't download the .pivotal file, but transfer it directly from pivnet to the opsmgr vm. And it's huge. Since it's impossible to read only a fragment of it from pivnet, it seems better to get the info from opsmgr somehow...
